#!/usr/bin/env python3
""" Skeleton Implementation of Project 2 for NEU CS3700 """

import argparse
import json
import select
import socket

##########################################################################################

# Message Fields
TYPE = "type"
SRCE = "src"
DEST = "dst"
MESG = "msg"
TABL = "table"

# Message Types
DATA = "data"
DUMP = "dump"
UPDT = "update"
RVKE = "revoke"
NRTE = "no route"

# Update Message Fields
NTWK = "network"
NMSK = "netmask"
ORIG = "origin"
LPRF = "localpref"
APTH = "ASPath"
SORG = "selfOrigin"

# internal route info
CUST = "cust"
PEER = "peer"
PROV = "prov"


##########################################################################################

class Router:
  """ Your Router """
  def __init__(self, asn, networks):
    self.asn = asn
    self.routes = {}
    self.updates = {}
    self.relations = {}
    self.sockets = {}
    for relationship in networks:
      network, relation = relationship.split("-")
      self.sockets[network] = socket.socket(socket.AF_UNIX, socket.SOCK_SEQPACKET)
      self.sockets[network].setblocking(0)
      self.sockets[network].connect(network)
      self.relations[network] = relation


  def lookup_routes(self, daddr):
    """ Lookup all valid routes for an address """
    # TODO
    ladd = daddr.split(".")
    ladd.pop(len(ladd) - 1)
    ladd.append(0)
    daddr = str(ladd[0]) + '.' + str(ladd[1]) + '.' + str(ladd[2]) + '.' + str(ladd[3])
    outroutes = [self.routes[daddr]]
    return outroutes

  def get_shortest_as_path(self, routes):
    """ select the route with the shortest AS Path """
    # TODO
    outroutes = []
    return routes

  def get_highest_preference(self, routes):
    """ select the route with the shortest AS Path """
    # TODO
    outroutes = []
    return routes

  def get_self_origin(self, routes):
    """ select self originating routes """
    # TODO
    outroutes = []
    return routes

  def get_origin_routes(self, routes):
    """ select origin routes: EGP > IGP > UNK """
    # TODO
    outroutes = []
    return routes

  def filter_relationships(self, srcif, routes):
    """ Don't allow Peer->Peer, Peer->Prov, or Prov->Peer forwards """
    outroutes = []
    return routes

  def get_route(self, srcif, daddr):
    """ Select the best route for a given address """
    # TODO
    peer = None
    routes = self.lookup_routes(daddr)
    # Rules go here
    if routes:
      # 1. Highest Preference
      routes = self.get_highest_preference(routes)
      # 2. Self Origin
      routes = self.get_self_origin(routes)
      # 3. Shortest ASPath
      routes = self.get_shortest_as_path(routes)
      # 4. EGP > IGP > UNK
      routes = self.get_origin_routes(routes)
      # 5. Lowest IP Address
      # TODO
      # Final check: enforce peering relationships
      routes = self.filter_relationships(srcif, routes)
      peer = routes[0]["peer"]
    return self.sockets[peer] if peer else None

#Added
  def send_data(self, srcif, packet):
      """find the route and send data message"""
      conn = self.get_route(srcif,packet['dst'])
      if(conn != None):
         msgout = json.dumps(packet)
         conn.sendall(msgout.encode())
         return True
      else:
         return False

  # Forwards the given packet to the surrounding sockets
  def forward(self, srcif, packet):
    """ Forward a data packet """
    packet['msg']['ASPath'].append(self.asn)

    # TODO Forward packets to people when the src is not a customer
    if self.relations[srcif] == 'cust':
      for sock in self.sockets:
        if sock != srcif:
          packet['src'] = sock.rstrip('2') + '1'
          packet['dst'] = sock
          
          conn = self.sockets[sock]      
          msgout = json.dumps(packet)
          conn.sendall(msgout.encode())
    else:
      print("Src not customer")
    return False

  def coalesce(self):
    """ coalesce any routes that are right next to each other """
    # TODO (this is the most difficult task, save until last)
    return False
  
  # Stores update message, forwards updates to neighbors if need be, updates forwarding table
  def update(self, srcif, packet):
    """ handle update packets """
    # TODO Verify that the storing of updates won't have overlapping entries
    # TODO Verify that the forwarding address will work in the case of overlapping entries
    self.updates[srcif] = packet

    rdic = {"network" : packet['msg']['network'], "netmask" : packet['msg']['netmask'], "peer" : srcif}
    self.routes[packet['msg']['network']] = rdic
    self.forward(srcif, packet)
    return True

  def revoke(self, packet):
    """ handle revoke packets """
    # TODO
    return True

  def dump(self, packet):
    """ handles dump table requests """
    # TODO
    
    tmp = packet["src"]
    packet["src"] = packet["dst"]
    packet["dst"] = tmp
    packet["type"] = "table"
    packet["msg"] = list(self.routes.values()) 
    
    conn = self.sockets[tmp]
    msgout = json.dumps(packet)
    conn.sendall(msgout.encode())

    return True
  
  # Receives the message from another router and send it to the correct handler method
  def handle_packet(self, srcif, packet):
    """ dispatches a packet """
    if packet['type'] == 'update':
      return self.update(srcif, packet)
    if packet['type'] == 'dump':
      return self.dump(packet)
    if packet['type'] == 'data':
      return self.send_data(srcif, packet)
    # TODO Route data, revoke, dump, and other messages to the correct handler
    return False
  
  # Send a no route message through the connection
  def send_error(self, conn, msg):
    """ Send a no_route error message """
    print("No route")
    # TODO
    return

  def run(self):
    """ main loop for the router """
    while True:
      socks = select.select(self.sockets.values(), [], [], 0.1)[0]
      for conn in socks:
        try:
          k = conn.recv(65535)
        except:
          # either died on a connection reset, or was SIGTERM's by parent
          return
        if k:
          for sock in self.sockets:
            if self.sockets[sock] == conn:
              srcif = sock
          msg = json.loads(k)
          if not self.handle_packet(srcif, msg):
            self.send_error(conn, msg)
        else:
          return

if __name__ == "__main__":
  PARSER = argparse.ArgumentParser(description='route packets')
  PARSER.add_argument('asn', metavar='asn', type=int, help="asn")
  PARSER.add_argument('networks', metavar='networks', type=str, nargs='+', help="networks")
  ARGS = PARSER.parse_args()
  Router(ARGS.asn,ARGS.networks).run()
